/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    BaseOverlay: typeof import('./src/components/BaseOverlay.vue')['default']
    BaseTabs: typeof import('./src/components/BaseTabs.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    Icon: typeof import('./src/components/icons/Icon.vue')['default']
    IconArrow: typeof import('./src/components/icons/IconArrow.vue')['default']
    IconDark: typeof import('./src/components/icons/IconDark.vue')['default']
    IconGrid: typeof import('./src/components/icons/IconGrid.vue')['default']
    IconHome: typeof import('./src/components/icons/IconHome.vue')['default']
    IconLight: typeof import('./src/components/icons/IconLight.vue')['default']
    IconSettings: typeof import('./src/components/icons/IconSettings.vue')['default']
    IconX: typeof import('./src/components/icons/IconX.vue')['default']
    KanaDisplay: typeof import('./src/components/KanaDisplay.vue')['default']
    KanaInput: typeof import('./src/components/KanaInput.vue')['default']
    KanaPart: typeof import('./src/components/KanaPart.vue')['default']
    OverlayKana: typeof import('./src/components/OverlayKana.vue')['default']
    OverlaySettings: typeof import('./src/components/OverlaySettings.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableHiragana: typeof import('./src/components/TableHiragana.vue')['default']
  }
}
